vim.g.netrw_banner = 0
vim.g.netrw_hide = 1
vim.g.netrw_liststyle = 3 -- Start in tree mode.
vim.o.autowrite = true
vim.o.belloff = "" -- Vim default.
vim.o.breakindent = true
vim.o.confirm = true -- Have destructive commands y-n prompt instead of fail.
vim.o.encoding = "utf-8"
vim.o.foldenable = false
vim.o.foldlevelstart = 99
vim.o.foldmethod = "indent"
vim.o.formatoptions = "roqlj" -- See fo-table.
vim.o.guicursor = ""
vim.o.hlsearch = true
vim.o.ignorecase = false
vim.o.joinspaces = false -- Single space after a period.
vim.o.laststatus = 1
vim.o.lazyredraw = true -- No redrawing while executing macros.
vim.o.linebreak = true
vim.o.list = false
vim.o.listchars = "tab:>  ,lead:-,trail:-,extends:@,precedes:@,nbsp:-"
vim.o.modeline = false
vim.o.mouse = ""
vim.o.nrformats = "alpha,bin,hex" -- Enable CTRL-A for letters, don't treat leading 0s as a base 8 marker.
vim.o.number = true
vim.o.report = 0 -- Always report number of lines changed, no arbitrary threshhold.
vim.o.secure = true -- Unnecesary but just in case, see trojan-horse.
vim.o.shiftround = true -- Round indent to shiftwidth.
vim.o.shiftwidth = 8
vim.o.showfulltag = true
vim.o.showmode = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.startofline = false
vim.o.textwidth = 80
vim.o.undofile = true
vim.o.virtualedit = "all" -- Viaje de ida.
vim.o.wrap = false
vim.o.wrapscan = false
